### ISSUE TITLE
Plugin does not show up in SDRSharp

### ISSUE THREAD

**Issue by antonrekun** [alan-de-windt/SDRSharpController#1]
Followed the instructions:
1. Created the **SDRSharp Controller** folder under **Plugins**
2. Placed the **SDRSharp.SDRSharpController.dll** into **SDRSharp Controller**
3. Started SDRSharp.

The plugin is unfortunately missing from the list of available plugins in SDRSharp.
I've tried adding another plugin - that one worked. Also tried putting the .dll in the Plugins folder, not in the SDRSharp Controller - same result.

Here is the listing of my Plugins folder:

Directory of C:\Program Files (x86)\sdrsharp-x86\Plugins
11/21/2023  05:44 PM    < DIR >          .
11/21/2023  05:44 PM    < DIR >          ..
11/21/2023  11:56 AM    < DIR >          SDRSharp Controller
11/06/2017  07:45 AM            78,848 SDRSharp.FrequencyScanner.dll

SDRSharp version: SDR# Studio v1.0.0.1862

Note: I do not currently have the physical device to use with this plugin. I did try to plug in an Arduino just so that my computer would list it as a serial device in hopes that the SDRSharpController plugin would see a serial device, in case if that's what was causing the issue. This did not help either.

**Comment by alan-de-windt** [comment]
Hi antonrekun,

I see that you tried this with version 1862.  I have not tested with this version, only with 1919 so please try it with this version if possible.  

I am not familiar with what the different versions support but I believe that starting with version 1919 (or perhaps a few versions before this?) it no longer became necessary to register a plugin in an XML configuration file.  There was also a significant change with the .NET version used to compile SDR# with the result that some plugins no longer work in 1919.  That is the case for me with the SDRSharp Net Remote plugin and is another reason why I decided to create my own plugin.

Also, I just retested with my version 1919 by completely removing the folder from the Plugins folder with the consequence that SDR# 1919 no longer shows the plugin when I start it, and then re-installing the folder with SDR# immediately recognizing the plugin once again.

Best regards,
Alan De Windt

**Comment by antonrekun** [comment]
Hi Alan,

Thanks for your suggestion! I've updated SDRSharp to version 1919 and your plugin now shows up in the list and loads correctly if selected.

Best regards, 
Anton
